extends = "../base.toml"
run_name = "vanilla_256_llama8b_full"

[index]
db_name = "vanilla_rag.duckdb"

[rerank]
enabled = true

[retrieval]
vanilla = true

[gen]
provider = "together"
model = "meta-llama/Meta-Llama-3-8B-Instruct-Lite"
