# Copyright (c) 2025 Kenneth Stott. MIT License.
# Canary: 594971fb-3c6b-4413-b60e-5c08437230ff
#
# NOTICE: Use of this software for training artificial intelligence or
# machine learning models is strictly prohibited without explicit written
# permission from the copyright holder.

import collections
import os
import re
import tomllib

PROJ = os.environ.get("PROJ", os.getcwd())
d = tomllib.load(open(f"{PROJ}/uv.lock", "rb"))
pkgs = d["package"]
root = next(p for p in pkgs if p.get("source", {}).get("editable") == "." or p["name"] == "chonk")
others = [p for p in pkgs if p is not root]
by_name = {p["name"]: p for p in others}

main_entry = [x["name"] for x in root.get("dependencies", [])]
extras = {k: [x["name"] for x in v] for k, v in root.get("optional-dependencies", {}).items()}
dev_entry = [x["name"] for g, v in root.get("dev-dependencies", {}).items() for x in v]
all_extra_pkgs = set().union(*[set(v) for v in extras.values()]) if extras else set()


def reach(seeds, unmarked_only=False):
    seen, stack = set(), list(seeds)
    while stack:
        n = stack.pop()
        if n in seen or n not in by_name:
            continue
        seen.add(n)
        for dep in by_name[n].get("dependencies", []):
            if unmarked_only and "marker" in dep:
                continue
            stack.append(dep["name"])
    return seen


main_nonopt = reach(main_entry)
main_all = reach(set(main_entry) | all_extra_pkgs)
dev_all = reach(dev_entry)
universal = reach(set(main_entry) | all_extra_pkgs | set(dev_entry), unmarked_only=True)

# which extras' closures include each package (for `extra == "..."` markers)
extras_including = collections.defaultdict(set)
for E, names in extras.items():
    for n in reach(names):
        extras_including[n].add(E)

# incoming markers per package (for non-universal ones)
inc = collections.defaultdict(set)
for p in others:
    for dep in p.get("dependencies", []):
        if "marker" in dep:
            inc[dep["name"]].add(dep["marker"])


def pkg_marker(name):
    if name in universal:
        return None
    ms = inc.get(name)
    if not ms:
        return None
    return next(iter(ms)) if len(ms) == 1 else " or ".join(f"({m})" for m in sorted(ms))


def key(name):
    return name if re.fullmatch(r"[A-Za-z0-9_-]+", name) else f'"{name}"'


def base(url):
    return url.rsplit("/", 1)[-1]


L = [
    "# This file is automatically @generated by Poetry 2.4.1 and should not be changed by hand.",
    "",
]
for p in sorted(others, key=lambda x: x["name"].lower()):
    name, ver = p["name"], p["version"]
    groups = [g for g, s in (("main", main_all), ("dev", dev_all)) if name in s] or ["main"]
    optional = (name in main_all) and (name not in main_nonopt) and (name not in dev_all)
    plat = pkg_marker(name)  # platform marker (e.g. sys_platform == 'linux'), or None
    if optional:
        exs = sorted(extras_including.get(name, []))
        extra_mk = " or ".join(f'extra == "{e}"' for e in exs) if exs else None
        if extra_mk and plat:
            marker = f"({extra_mk}) and ({plat})"
        else:
            marker = extra_mk or plat
    else:
        marker = plat
    L += [
        "[[package]]",
        f'name = "{name}"',
        f'version = "{ver}"',
        'description = ""',
        f"optional = {'true' if optional else 'false'}",
        'python-versions = "*"',
        "groups = [" + ", ".join(f'"{g}"' for g in groups) + "]",
    ]
    if marker:
        L.append('markers = "' + marker.replace('"', '\\"') + '"')
    files = []
    sd = p.get("sdist")
    if sd and "url" in sd:
        files.append((base(sd["url"]), sd["hash"]))
    for w in p.get("wheels", []):
        files.append((base(w["url"]), w["hash"]))
    L.append("files = [")
    L += [f'    {{file = "{fn}", hash = "{h}"}},' for fn, h in files]
    L.append("]")
    deps = p.get("dependencies", [])
    if deps:
        L += ["", "[package.dependencies]"]
        for dep in deps:
            dn, m2, ex = dep["name"], dep.get("marker"), dep.get("extra")
            if ex or m2:
                parts = ['version = "*"']
                if ex:
                    parts.append("extras = [" + ", ".join(f'"{e}"' for e in ex) + "]")
                if m2:
                    parts.append(f'markers = "{m2}"')
                L.append(f"{key(dn)} = {{" + ", ".join(parts) + "}")
            else:
                L.append(f'{key(dn)} = "*"')
    L.append("")

L.append("[extras]")
for ex in sorted(extras):
    L.append(f"{ex} = [" + ", ".join(f'"{n}"' for n in extras[ex]) + "]")
L.append("")

# content-hash via poetry-core
from poetry.factory import Factory  # noqa: E402

chash = Factory().create_poetry(PROJ).locker._get_content_hash()

L += [
    "[metadata]",
    'lock-version = "2.1"',
    'python-versions = ">=3.11,<3.15"',
    f'content-hash = "{chash}"',
    "",
]

open("/tmp/chonk_poetry.lock", "w").write("\n".join(L))
print(f"wrote {len(others)} packages; content-hash={chash}")
print(
    f"groups: main_nonopt={len(main_nonopt)} main_all={len(main_all)} dev_all={len(dev_all)} universal={len(universal)}"  # noqa: E501
)
print(f"non-universal (platform-marked) packages: {sorted(set(by_name) - universal)}")
