// Package ner provides named entity recognition via Together.ai.
//
// MIGRATION MARKER: Ported from chonk/ner/ sub-package.
// Python sources:
//   - chonk/ner/_pipeline.py  (280 LOC) — NerPipeline
//   - chonk/ner/_index.py               — EntityIndex
//   - chonk/ner/_vocabulary.py          — VocabularyMatcher, EntityMatch
//   - chonk/ner/_merge.py               — merge_matches()
//   - chonk/ner/_normalizer.py          — normalize_schema_term()
//   - chonk/ner/_schema.py              — SchemaMatcher
//   - chonk/ner/_schema_vocab.py        — SchemaVocabBuilder
//   - chonk/ner/_spacy.py               — SpacyMatcher → replaced by Together.ai
//
// Status: Interfaces + EntityIndex + EntityMatch COMPLETE; NerPipeline stub.
//
// Key design change (ADR ml-services.md):
//   Python spacy + thinc → Together.ai Chat API (JSON-mode NER prompt).
//   The SpacyMatcher no longer exists. Together.ai returns structured JSON
//   that is parsed into []EntityMatch, matching the Python output contract.
package ner

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"unicode"

	"github.com/kennethstott/chonk/internal/together"
)

// EntityMatch is a single named entity identified in text.
// Python source: ner._vocabulary.EntityMatch
type EntityMatch struct {
	EntityID   string // from vocabulary, or generated by Together.ai
	Name       string // surface form found in text
	EntityType string // "concept" | "org" | "person" | "location" | "product" | etc.
	Start      int    // character offset start in the source text
	End        int    // character offset end (exclusive)
	Score      float64
}

// EntityIndex maps chunk IDs to their entity matches.
// Python source: ner._index.EntityIndex
type EntityIndex struct {
	// chunkEntities: chunk_id → []EntityMatch
	chunkEntities map[string][]EntityMatch
	// entityChunks: entity_id → []chunk_id (reverse index)
	entityChunks map[string][]string
}

// NewEntityIndex creates an empty EntityIndex.
func NewEntityIndex() *EntityIndex {
	return &EntityIndex{
		chunkEntities: make(map[string][]EntityMatch),
		entityChunks:  make(map[string][]string),
	}
}

// IndexChunk records which entities appear in a chunk.
// Python source: ner._index.EntityIndex.index_chunk()
func (idx *EntityIndex) IndexChunk(chunkID string, matches []EntityMatch) {
	idx.chunkEntities[chunkID] = matches
	for _, m := range matches {
		idx.entityChunks[m.EntityID] = append(idx.entityChunks[m.EntityID], chunkID)
	}
}

// ChunksForEntity returns all chunk IDs containing the given entity.
// Python source: ner._index.EntityIndex.chunks_for_entity()
func (idx *EntityIndex) ChunksForEntity(entityID string) []string {
	return idx.entityChunks[entityID]
}

// EntitiesForChunk returns all matches for a chunk.
// Python source: ner._index.EntityIndex.entities_for_chunk()
func (idx *EntityIndex) EntitiesForChunk(chunkID string) []EntityMatch {
	return idx.chunkEntities[chunkID]
}

// ── NerPipeline ───────────────────────────────────────────────────────────────

// NerPipeline runs NER using the Together.ai API in JSON-mode.
// Python source: ner._pipeline.NerPipeline
//
// Replaces: VocabularyMatcher + SpacyMatcher two-pass pipeline.
// The Together.ai response is parsed into []EntityMatch, preserving the
// same output contract expected by EntityIndex.IndexChunk.
type NerPipeline struct {
	client      *together.Client
	entityTypes []string // entity types to extract (e.g. ["org", "person", "product"])
}

// NewNerPipeline creates a NerPipeline backed by the Together.ai client.
// entityTypes: the NER labels to request (nil → default set).
func NewNerPipeline(client *together.Client, entityTypes []string) *NerPipeline {
	if len(entityTypes) == 0 {
		entityTypes = []string{"organization", "person", "location", "product", "technology", "concept"}
	}
	return &NerPipeline{client: client, entityTypes: entityTypes}
}

// Extract runs NER on text and returns matched entities.
// Python source: ner._pipeline.NerPipeline.match()
//
// MIGRATION NOTE: Python's two-pass (VocabularyMatcher priority over SpacyMatcher)
// is replaced by a single Together.ai call with a structured JSON prompt.
// Entity type labels are harmonised to the Python spaCy label set where possible.
func (p *NerPipeline) Extract(ctx context.Context, text string) ([]EntityMatch, error) {
	if strings.TrimSpace(text) == "" {
		return nil, nil
	}
	prompt := buildNERPrompt(text, p.entityTypes)
	msgs := []together.Message{
		{Role: "system", Content: "You are a precise named entity recognition system. Return only valid JSON."},
		{Role: "user", Content: prompt},
	}
	reply, err := p.client.Chat(ctx, msgs, &together.ChatOptions{
		MaxTokens: 2048,
		JSONMode:  true,
	})
	if err != nil {
		return nil, fmt.Errorf("ner extract: %w", err)
	}
	return parseNERReply(reply, text)
}

// ── helpers ───────────────────────────────────────────────────────────────────

func buildNERPrompt(text string, entityTypes []string) string {
	types := strings.Join(entityTypes, ", ")
	return fmt.Sprintf(`Extract named entities from the text below.

Entity types to extract: %s

Return a JSON object with a single key "entities" containing an array of objects.
Each object must have: "name" (string), "entity_type" (string), "start" (int), "end" (int).

Text:
%s`, types, text)
}

// nerAPIEntity is the raw JSON shape returned by Together.ai.
type nerAPIEntity struct {
	Name       string `json:"name"`
	EntityType string `json:"entity_type"`
	Start      int    `json:"start"`
	End        int    `json:"end"`
}

func parseNERReply(reply, sourceText string) ([]EntityMatch, error) {
	var parsed struct {
		Entities []nerAPIEntity `json:"entities"`
	}
	if err := json.Unmarshal([]byte(reply), &parsed); err != nil {
		return nil, fmt.Errorf("ner parse: %w (raw: %s)", err, truncate(reply, 200))
	}
	matches := make([]EntityMatch, 0, len(parsed.Entities))
	for _, e := range parsed.Entities {
		if e.Name == "" {
			continue
		}
		// Validate offsets against source text
		start, end := e.Start, e.End
		if start < 0 || end > len(sourceText) || start >= end {
			// Fallback: find first occurrence by string search
			idx := strings.Index(sourceText, e.Name)
			if idx < 0 {
				continue
			}
			start = idx
			end = idx + len(e.Name)
		}
		matches = append(matches, EntityMatch{
			EntityID:   stableID(e.Name, e.EntityType),
			Name:       e.Name,
			EntityType: e.EntityType,
			Start:      start,
			End:        end,
			Score:      1.0,
		})
	}
	return matches, nil
}

// MergeMatches deduplicates and resolves overlapping entity matches by keeping
// the highest-scoring non-overlapping match. Equivalent to merge_matches() in Python.
// Python source: ner._merge.merge_matches()
func MergeMatches(matches []EntityMatch) []EntityMatch {
	if len(matches) == 0 {
		return nil
	}
	// Sort by start position (stable — preserve insertion order for ties)
	sorted := make([]EntityMatch, len(matches))
	copy(sorted, matches)
	sortByStart(sorted)

	var result []EntityMatch
	for _, m := range sorted {
		if len(result) == 0 {
			result = append(result, m)
			continue
		}
		last := result[len(result)-1]
		if m.Start < last.End {
			// Overlap: keep higher-scoring one
			if m.Score > last.Score {
				result[len(result)-1] = m
			}
		} else {
			result = append(result, m)
		}
	}
	return result
}

// NormalizeSchemaTermm converts camelCase / snake_case identifiers to readable prose.
// Python source: ner._normalizer.normalize_schema_term()
// Examples: "firstName" → "first name", "ACCOUNT_ID" → "account id"
func NormalizeSchemaTermm(term string) string {
	// snake_case
	term = strings.ReplaceAll(term, "_", " ")
	// SCREAMING_SNAKE → lower
	if strings.ToUpper(term) == term {
		return strings.ToLower(term)
	}
	// camelCase → insert space before each uppercase run
	re := regexp.MustCompile(`([a-z])([A-Z])`)
	term = re.ReplaceAllString(term, "$1 $2")
	return strings.ToLower(strings.TrimSpace(term))
}

// ── sort helper (insertion sort — slices are small) ──────────────────────────

func sortByStart(ms []EntityMatch) {
	for i := 1; i < len(ms); i++ {
		j := i
		for j > 0 && ms[j].Start < ms[j-1].Start {
			ms[j], ms[j-1] = ms[j-1], ms[j]
			j--
		}
	}
}

// stableID derives a stable entity ID from name + type.
func stableID(name, entityType string) string {
	safe := strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return unicode.ToLower(r)
		}
		return '_'
	}, name)
	return entityType + "_" + safe
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
